language: python

cache: pip

python:
    - "3.6"

install:
    - pip install --upgrade setuptools pip
    - pip install -r src/requirements.txt -r src/requirements/dev.txt

before_script:
    - cd src

script:
    - flake8 c3nav
    - isort -c -rc .
    - python manage.py migrate
    - python manage.py collectstatic --noinput
    - python manage.py compress
